# Redirect with a 301
[[redirects]]
from = "/home"
to = "/"
status = 301

# Redirect with a 302
[[redirects]]
from = "/my-redirect"
to = "/"
status = 302

# Show a custom 404 for this path
[[redirects]]
from = "/index.php"
to = "/store-closed"
status = 404

# Rewrite a path
[[redirects]]
from = "/pass-through"
to = "/index.php"
status = 200
